FROM influxdb:1.5

ENV INFLUXDB_HTTP_AUTH_ENABLED="true" \
    INFLUXDB_ADMIN_USER="influx_user" \
    INFLUXDB_ADMIN_PASSWORD="influx_password"

ENV INFLUXDB_UDP_ENABLED="true" \
    INFLUXDB_UDP_BIND_ADDRESS=":8086" \
    INFLUXDB_UDP_DATABASE="_test_database_udp" \
    INFLUXDB_UDP_BATCH_SIZE="1" \
    INFLUXDB_UDP_BATCH_TIMEOUT="1ms" \
    INFLUXDB_UDP_BATCH_PENDING="1"
